import { StayItem } from "@/components/StayCard";

export const STAYS_DATA: StayItem[] = [
  {
    id: "stay-1",
    title: "Kanthalur Heritage Mud House",
    category: "Mud House",
    image: "/stays/res1.jpeg",
    rating: "4.9",
    reviews: "112",
    description: "Authentic traditional eco mud house surrounded by organic apple trees and high-altitude mist. Offers natural room cooling and organic home-cooked Kerala meals.",
    amenities: ["Mud Cottage", "Organic Meals", "Campfire", "Mountain View"],
  },
  {
    id: "stay-2",
    title: "Orchard View Highland Homestay",
    category: "Homestay",
    image: "/stays/res2.jpeg",
    rating: "4.8",
    reviews: "85",
    description: "Warm family-run homestay situated amidst plum & apple orchards. Experience genuine highland hospitality and guided fruit garden walks.",
    amenities: ["Orchard Walk", "Home Cooked Food", "Free Wi-Fi", "Balcony View"],
  },
  {
    id: "stay-3",
    title: "Kanthalur Valley Nature Resort",
    category: "Resort",
    image: "/stays/res3.jpeg",
    rating: "4.9",
    reviews: "140",
    description: "Boutique luxury resort overlooking panoramic green valley peaks with cozy wooden suites, campfire nights, and off-road jeep safari desk.",
    amenities: ["Valley View", "Restaurant", "Jeep Safari Desk", "Hot Water"],
  },
  {
    id: "stay-4",
    title: "Highland Strawberry Treehouse",
    category: "Treehouse",
    image: "/stays/res4.jpeg",
    rating: "5.0",
    reviews: "64",
    description: "Unique elevated wooden treehouse built above lush strawberry fields offering unmatched privacy, mist views, and starlight dining.",
    amenities: ["Canopy View", "Private Deck", "Starlight Dining", "Parking"],
  },
  {
    id: "stay-5",
    title: "Pine Forest Mountain Cottage",
    category: "Cottage",
    image: "/stays/res5.jpeg",
    rating: "4.8",
    reviews: "76",
    description: "Secluded wooden cabin surrounded by whispering pine trees and cool mountain breezes. Perfect for peaceful romantic or family escapes.",
    amenities: ["Pine Forest View", "Private Lawn", "Campfire", "Trekking Desk"],
  },
  {
    id: "stay-6",
    title: "Apple Garden Villa & Stay",
    category: "Villa",
    image: "/stays/res6.jpeg",
    rating: "4.9",
    reviews: "92",
    description: "Spacious luxury villa in the heart of Kanthalur apple country with expansive private lawns, terrace views, and modern comforts.",
    amenities: ["Private Lawn", "Spacious Villa", "Apple Garden", "Barbecue"],
  },
  {
    id: "stay-7",
    title: "Mist Valley Eco Lodge",
    category: "Eco Lodge",
    image: "/stays/res7.jpeg",
    rating: "4.8",
    reviews: "58",
    description: "Eco-friendly nature lodge tucked into serene mist-covered slopes. Perfect for bird watching, morning fog walks, and star gazing.",
    amenities: ["Eco Stay", "Bird Watching", "Solar Power", "Guided Walks"],
  },
  {
    id: "stay-8",
    title: "Highland Panorama Cottage",
    category: "Cottage",
    image: "/stays/res8.jpeg",
    rating: "4.9",
    reviews: "104",
    description: "Charming highland cottage with 360-degree views of Anamudi peaks and terraced farm valleys. Includes private campfire setup.",
    amenities: ["360 Peak View", "Campfire Setup", "Family Suite", "Room Service"],
  },
];
